development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_dev
  host: localhost
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_test
  host: localhost
  pool: 5
  username: root
  password: 