# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 694e57b53b552361d87b3dc409c7b6491f797c732e435b99c6adaa716e14ebdfc3981bd67cd73ef28843fa68f68ec24945f229ec7fbeb5345f390f71581aecdb

test:
  secret_key_base: 1e9a1e987f882d04993c2096cf04f2e2bbdb7a652cae5f9486c35e20e444b7f2242907fa8eb00f0a00ac3de79ee4600c27ed84cb5ac52aa7109d4fc353f5345b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
